package dev.slne.surf.api.shared.api.reflection

import java.lang.reflect.Modifier
import kotlin.reflect.KClass


/**
 * Returns the generated reflection implementation for [T].
 *
 * This function is intended for companion-object delegation inside interfaces annotated with
 * [GenerateReflection]&#58;  *
 * ```kotlin
 * @GenerateReflection
 * interface ExampleReflection {
 *     companion object : ExampleReflection by generatedReflectionAccessor<ExampleReflection>()
 * }
 * ```
 *
 * The generated implementation class is loaded by convention from the [GenerateReflection]
 * annotation. If no custom class name is configured, the implementation name is
 * `<InterfaceSimpleName>Impl` in the interface package.
 *
 * This function does not generate code at runtime. The implementation must still be generated by
 * KSP during compilation.
 *
 * @throws IllegalArgumentException if [T] is not an interface or is missing [GenerateReflection].
 * @throws IllegalStateException if the generated implementation class cannot be loaded or does not
 * implement [T].
 */
inline fun <reified T : Any> generatedReflectionAccessor(): T {
    return GeneratedReflectionAccessors.getTyped(T::class.java)
}

/**
 * Returns the generated reflection implementation for [type].
 *
 * Prefer the reified [generatedReflectionAccessor] overload from Kotlin code.
 */
fun <T : Any> generatedReflectionAccessor(type: KClass<T>): T {
    return GeneratedReflectionAccessors.getTyped(type.java)
}

/**
 * Returns the generated reflection implementation for [type].
 *
 * Prefer the reified [generatedReflectionAccessor] overload from Kotlin code.
 */
fun <T : Any> generatedReflectionAccessor(type: Class<T>): T {
    return GeneratedReflectionAccessors.getTyped(type)
}

/**
 * Runtime loader and cache for generated reflection implementations.
 */
@PublishedApi
internal object GeneratedReflectionAccessors : ClassValue<Any>() {

    override fun computeValue(type: Class<*>): Any? {
        return type.cast(createAccessor(type))
    }

    fun <T : Any> getTyped(type: Class<T>): T {
        return type.cast(get(type))
    }

    private fun createAccessor(type: Class<*>): Any {
        require(type.isInterface) {
            "Generated reflection accessors can only be loaded for interfaces: ${type.name}"
        }

        val annotation = type.getAnnotation(GenerateReflection::class.java)
            ?: throw IllegalArgumentException(
                "Missing @${GenerateReflection::class.java.simpleName}: on ${type.name}"
            )

        val implementationClassName = annotation.implementationClassName(type)

        val implementationClass = try {
            Class.forName(implementationClassName, true, type.classLoader)
        } catch (exception: ClassNotFoundException) {
            throw IllegalStateException(
                "Generated reflection implementation '$implementationClassName' was not found for '${type.name}'. " +
                        "Run the KSP task for the module that declares this interface.",
                exception,
            )
        }

        check(type.isAssignableFrom(implementationClass)) {
            "Generated reflection implementation '${implementationClass.name}' does not implement '${type.name}'"
        }

        return implementationClass.readSingletonInstance() ?: implementationClass.createNewInstance()
    }

    private fun GenerateReflection.implementationClassName(interfaceClass: Class<*>): String {
        val implementationPackage = packageName.ifBlank { interfaceClass.packageName }
        val implementationSimpleName = className.ifBlank { "${interfaceClass.simpleName}Impl" }

        return if (implementationPackage.isBlank()) {
            implementationSimpleName
        } else {
            "$implementationPackage.$implementationSimpleName"
        }
    }

    private fun Class<*>.readSingletonInstance(): Any? {
        val field = runCatching { getField("INSTANCE") }.getOrNull() ?: return null

        if (!Modifier.isStatic(field.modifiers)) {
            return null
        }

        return field.get(null)
    }

    private fun Class<*>.createNewInstance(): Any {
        val constructor = runCatching { getDeclaredConstructor() }.getOrElse { exception ->
            throw IllegalStateException(
                "Generated reflection implementation '$name' has no INSTANCE field and no no-args constructor.",
                exception,
            )
        }

        constructor.trySetAccessible()
        return constructor.newInstance()
    }
}