guava=${versions.guava}
caffeine=${versions.caffeine}
gson=${versions.gson}
commons-lang3=${versions.commons-lang3}
commons-text=${versions.commons-text}
packet-events-spigot=${versions.packet-events-spigot}
entity-lib=${versions.entity-lib}
scoreboard-lib=${versions.scoreboard-library}