package dev.slne.surf.surfapi.core.api.packet.entity.entities.living;

import com.github.retrooper.packetevents.protocol.player.HumanoidArm;
import dev.slne.surf.surfapi.core.api.packet.entity.annotation.NeedsRespawn;
import dev.slne.surf.surfapi.core.api.packet.entity.annotation.Useless;
import dev.slne.surf.surfapi.core.api.packet.entity.entities.PacketEntity;
import java.util.Optional;
import net.kyori.adventure.text.format.TextColor;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.spongepowered.math.vector.Vector3i;

public interface PacketLivingEntity<Impl extends PacketLivingEntity<Impl>> extends
    PacketEntity<Impl> {

  int LIVING_ENTITY_BIT_MASK_INDEX = 8, HEALTH_INDEX = 9, POTION_EFFECT_COLOR_INDEX = 10,
      POTION_EFFECT_AMBIENT_INDEX = 11, NUMBER_OF_ARROWS_INDEX = 12, NUMBER_OF_BEE_STINGERS_INDEX = 13,
      BED_LOCATION_INDEX = 14;

  byte HAND_ACTIVE_BIT = 0x01, ACTIVE_HAND_BIT = 0x02, IN_RIPTIDE_ATTACK_BIT = 0x04;

  /**
   * Head pitch
   */
  float headPitch();

  /**
   * Set head pitch
   *
   * @param headPitch head pitch
   */
  @NeedsRespawn
  void headPitch(float headPitch);

  /**
   * Is hand active
   */
  boolean handActive();

  /**
   * Set hand active
   */
  void handActive(boolean handActive);

  /**
   * The active hand
   *
   * @return active hand
   */
  HumanoidArm activeHand();

  /**
   * Sets the active hand
   *
   * @param activeHand the active hand
   */
  void activeHand(@NotNull HumanoidArm activeHand);

  /**
   * Is in riptide spin attack
   */
  boolean inRiptideAttack();

  /**
   * Set is in riptide spin attack
   */
  void inRiptideAttack(boolean inRiptideAttack);

  /**
   * Health (useless)
   */
  @Useless
  float health();

  /**
   * Sets the health (useless)
   */
  @Useless
  void health(float health);

  /**
   * Potion effect color (or {@link TextColor}{@code .color(0)} if there is no effect)
   */
  TextColor potionEffectColor();

  /**
   * Potion effect color (or {@code null} if there is no effect)
   */
  void potionEffectColor(@Nullable TextColor potionEffectColor);

  /**
   * Is potion effect ambient: reduces the number of particles generated by potions to {@code 1/5}
   * of the normal amount.
   */
  boolean potionEffectAmbient();

  /**
   * Is potion effect ambient: reduces the number of particles generated by potions to {@code 1/5}
   * of the normal amount.
   */
  void potionEffectAmbient(boolean potionEffectAmbient);

  /**
   * Number of arrows in entity
   */
  int numberOfArrows();

  /**
   * Number of arrows in entity
   */
  void numberOfArrows(int numberOfArrows);

  /**
   * Number of bee stingers in entity
   */
  int numberOfBeeStingers();

  /**
   * Number of bee stingers in entity
   */
  void numberOfBeeStingers(int numberOfBeeStingers);

  /**
   * Location of the bed the entity is currently sleeping in (Empty if it isn't sleeping)
   */
  @Useless
  Optional<Vector3i> bedLocation();

  /**
   * Location of the bed the entity is currently sleeping in ({@code null} if it isn't sleeping)
   */
  @Useless
  void bedLocation(@Nullable Vector3i bedLocation);
}
