package dev.slne.surf.api.minestom.plugin

import kotlinx.serialization.Serializable

/**
 * Describes a plugin, as read from its `minestom-plugin.json`.
 *
 * The file is generated by the `dev.slne.surf.api.gradle.minestom` Gradle plugin:
 *
 * ```
 * minestomPluginFile {
 *     main = "dev.slne.example.ExamplePlugin"
 *     authors = listOf("red")
 *
 *     pluginDependencies {
 *         register("surf-core-minestom")
 *         register("surf-chat-minestom") { optional = true }
 *     }
 * }
 * ```
 */
@Serializable
data class PluginMeta(
    /** Identifies the plugin; lowercase letters, digits, `-` and `_`. */
    val id: String,

    /** The fully qualified name of the class extending [SurfMinestomPlugin]. */
    val main: String,

    val name: String = id,
    val version: String = "unknown",
    val description: String = "",
    val url: String? = null,
    val authors: List<String> = emptyList(),

    /** The plugins this plugin needs, which are loaded and enabled before it. */
    val dependencies: List<PluginDependency> = emptyList(),
) {
    init {
        require(ID_REGEX.matches(id)) { "Invalid plugin id '$id', it has to match $ID_REGEX" }
        require(main.isNotBlank()) { "The plugin '$id' declares no main class" }
    }

    companion object {
        /** The file a plugin jar carries its [PluginMeta] in. */
        const val FILE_NAME = "minestom-plugin.json"

        /**
         * Lists the main classes of the plugins on the server's own class path, one per line.
         *
         * A service file, so that it survives when several plugins are shaded into one server jar.
         */
        const val CLASSPATH_INDEX = "META-INF/services/dev.slne.surf.api.minestom.plugin.SurfMinestomPlugin"

        /** Where a plugin on the class path keeps its [PluginMeta], as `<main class>.json`. */
        const val CLASSPATH_DIRECTORY = "META-INF/surf-minestom-plugins/"

        val ID_REGEX = Regex("[a-z][a-z0-9-_]{0,63}")
    }
}

/**
 * A plugin another plugin depends on.
 */
@Serializable
data class PluginDependency(
    val id: String,

    /** Whether the depending plugin also loads without this one. */
    val optional: Boolean = false,
)
