name: SurfAPIBukkit
api-version: '1.20'
version: ${project.version}
description: 'An API for surf servers.'
website: '${project.url}'

authors:
  - twisti

main: 'dev.slne.surf.surfapi.bukkit.server.BukkitMain'
bootstrapper: 'dev.slne.surf.surfapi.bukkit.server.BukkitBoostrapper'
loader: 'dev.slne.surf.surfapi.bukkit.server.BukkitLoader'

dependencies:
  server:
    ProtocolLib:
      load: BEFORE
      join-classpath: true
      required: false
    ProtocolSupport:
      load: BEFORE
      join-classpath: true
      required: false
    ViaVersion:
      load: BEFORE
      join-classpath: true
      required: false
    ViaBackwards:
      load: BEFORE
      join-classpath: true
      required: false
    ViaRewind:
      load: BEFORE
      join-classpath: true
      required: false
    Geyser-Spigot:
      load: BEFORE
      join-classpath: true
      required: false