name: Publish Dokka Docs

permissions:
  actions: write
  pages: write



on:
  push:
    branches:
      - version/1.21

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'graalvm'
          java-version: '21'

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Install dependencies
        run: ./gradlew dependencies

      - name: Generate and move Dokka Docs
        run: ./gradlew publishDokkaToDocs

      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs
          git commit -m "Update Dokka Docs"
          git push