name: Publish to Maven

on:
  push:
    branches:
      - version/1.21
  workflow_dispatch:

env:
  SLNE_SNAPSHOTS_REPO_USERNAME: ${{ secrets.SLNE_SNAPSHOTS_REPO_USERNAME }}
  SLNE_SNAPSHOTS_REPO_PASSWORD: ${{ secrets.SLNE_SNAPSHOTS_REPO_PASSWORD }}

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'graalvm'
          java-version: '21'
      - name: Build with Gradle
        run: ./gradlew shadowJar
      - name: Publish to Maven
        run: ./gradlew publish